
## This is a SAMPLE metadata file for a GitHub Action.  For more info:
##    https://help.github.com/en/articles/metadata-syntax-for-github-actions

name: lines-of-code-reporter
author: Pavan Mudigonda
description: |
  Calculates and publishes JaCoCo lines of code report in GitHub Actions as Checksuite.

## Here you describe your *formal* inputs -- those that are
## documented and can be displayed by the marketplace.
## You also use these to identify the *required* inputs.
inputs:

  directory:
    description: |
      Path to the JaCoCo coverage results file which will be used to generate
      a report. The only coverage results format supported is the
      JaCoCo XML schema.
    required: false
    default: ./

  exclude_dir:
    description: |
      # directories to be excluded.
    required: false

  exclude_lang:
    description: |
      # languages to be excluded.comma separated.
    required: false

  github_token:
    description: |
      GITHUB_TOKEN to authenticate against API calls to attach
      report to Workflow Run.
    required: false
    
  skip_check_run:
    description: |
      If true, will skip attaching the Tests Result report to
      the Workflow Run using a Check Run.  Useful if you just
      want to produce a Gist-based report via the `gist_name`
      and `gist_token` input parameters.
    required: false

## Here you describe your *formal* outputs.
outputs:

  loc_report:
    description: Output report in markdown

  total_lines:
    description: Total Lines of Code

  check_run_id:
    description: check run id of the report

  check_run_url:
    description: check run url of the report
    



branding:
  color: purple
  icon: check-circle

## Even though the Action logic may be implemented
## in PWSH, we still need a NodeJS entry point
runs:
  using: node12
  main: _init/index.js
