
## This is a SAMPLE metadata file for a GitHub Action.  For more info:
##    https://help.github.com/en/articles/metadata-syntax-for-github-actions

name: lines-of-code-reporter
author: Pavan Mudigonda
description: |
  Calculates and publishes JaCoCo lines of code report in GitHub Actions as Checksuite.

## Here you describe your *formal* inputs -- those that are
## documented and can be displayed by the marketplace.
## You also use these to identify the *required* inputs.
inputs:

  directory:
    description: |
      Path to the Directory where Calculation needs to run. Defaults to github workspace.
    required: false
    default: ${{ github.workspace }}

  exclude_dir:
    description: |
      # directories to be excluded. Comma separated allowed currently
    required: false
    default: ./dummy-folder-non-existent

  exclude_lang:
    description: |
      # languages to be excluded. Comma separated allowed currently. 
    required: false
    default: .

  include_lang:
    description: |
      # languages to be included. Comma separated allowed currently.
    required: false

  github_token:
    description: |
      GITHUB_TOKEN to authenticate against API calls to attach
      report to Workflow Run.
    required: false
    
  skip_check_run:
    description: |
      If true, will skip attaching the Tests Result report to
      the Workflow Run using a Check Run.  Useful if you just
      want to produce a Gist-based report via the `gist_name`
      and `gist_token` input parameters.
    required: false

## Here you describe your *formal* outputs.
outputs:

  loc_report:
    description: Output report in markdown

  total_lines_string:
    description: Total Lines of Code String Comma Seperated

  total_lines_int:
    description: Total Lines of Code int
    
  check_run_id:
    description: check run id of the report

  check_run_url:
    description: check run url of the report
    

branding:
  color: purple
  icon: check-circle

## Even though the Action logic may be implemented
## in PWSH, we still need a NodeJS entry point
runs:
  using: node12
  main: _init/index.js
