name: test

on:
  push:
  release:
    types: published

jobs:

  run-tests:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: use this action, with existing test results
        uses: PavanMudigonda/lines-of-code-reporter@v0.0.8
        with:
          directory: ./
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
      - name: print output
        run: | 
          echo "lines"
          echo $total_lines
          echo "file"
          echo $loc_report
        
